# @package _global_
batch_size: 4
num_workers: 8

# seed for random number generators in pytorch, numpy and python.random
seed: 2023

# monitor metric
monitor: "RMSE"

base_lr: 0.001

dataset: wuhan

center_pose: False
dist: False

scene: 8
start: 0
end: 0
voxel_size: 0.3
near: 0.5
far: 100
sample_radius: 0.5
samples_all: 32
chunk_size: 2048
random_points_num_vis: 4000
random_points_num_novis: 2000
N_rays: 4096
train_interval: 1
val_interval: 100

output_root: results/whu3d
superpoint_root: data/whu3d/superpoint
visible_root: data/whu3d/superpoint
points_root: data/whu3d/point_cloud
height_scale: 20
pts_feats_num: 128
pts_num_per_sp: 1024
pad_nums: 0
depth_threhold: 40
use_1th_cam: False
use_confidence: True
use_point_color: False
use_point_intensity: True
random_superpoint_nums: 500
pretrained_2d_model: mask2former  #['mask2former', 'segformer', 'deeplab']
use_sky: False
class_num: 10

train_params:
  weight_color: 1.0
  lambda_semantic_2d: 1.0
  semantic_weight : 0.03
  lambda_depth: 0.1 